matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode7.3
#      rvm:
#        # 2.3 isn't supported in Travis CI
#        - 2.2
      cache:
        directories:
          - node_modules
      before_install:
#        - brew update && brew upgrade
        - brew install nodejs
        - brew install watchman
        - brew install flow
      install:
        - npm install
#        - gem install bundler
#        - bundle install
#        - bundle exec pod install
      before_script:
        - cp .env.example .env
        - cd ios

      script:
        # TODO test
        - xcodebuild -configuration Release build -scheme YokohamaPM25React -destination 'platform=iOS Simulator,name=iPhone 6'

    - os: linux
      language: android
      before_cache:
        - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - node_modules
      android:
        components:
          # Uncomment the lines below if you want to
          # use the latest revision of Android SDK Tools
          - platform-tools
          - tools

          # The BuildTools version used by your project
          - build-tools-23.0.1

          # The SDK version used to compile your project
          - android-23

          # Additional components
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-23

          # Specify at least one system image,
          # if you need to run emulator(s) during your tests
          - sys-img-armeabi-v7a-android-23
          - sys-img-x86-android-23

      env:
        - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
        - TRAVIS_NODE_VERSION="5"

      install:
        - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
        - npm install

      before_script:
        - cp travis/dummy-release-key.keystore android/app/my-release-key.keystore
        - mkdir -p $HOME/.gradle
        - cp travis/gradle.properties $HOME/.gradle/gradle.properties
        - cp .env.example .env
        # Emulator Management: Create, Start and Wait
        # - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
        # - emulator -avd test -no-audio -no-window &
        # - android-wait-for-emulator
        # - adb shell input keyevent 82 &
      script:
        - cd android && ./gradlew assembleRelease